Change name

diff --git a/tools/reload b/tools/reload
--- a/tools/reload
+++ b/tools/reload
@@ -16,7 +16,7 @@ fi
 label="{${DJANGO_SETTINGS_MODULE#settings.}}ezid_base_url"
 hostname=$(grep -m1 "^${label}: [^ ]" $(dirname $0)/../settings/ezid.conf)
 if [ "$hostname" == "" ]; then
-  echo "$0: failed to locate EZID hostname" 1>&2
+  echo "$0: failed to locate ARKetype hostname" 1>&2
   exit 1
 fi
 hostname=${hostname#*: }
@@ -24,7 +24,7 @@ hostname=${hostname#*: }
 shadowfile=$(dirname $0)/../settings/ezid.conf.shadow
 password="$(grep -m1 '^admin_password: [^ ]' $shadowfile)"
 if [ "$password" == "" ]; then
-  echo "$0: failed to locate EZID administrator password" 1>&2
+  echo "$0: failed to locate ARKetype administrator password" 1>&2
   exit 1
 fi
 password="${password#*: }"
